### ISSUE TITLE
Convert to swift 4

### ISSUE THREAD

**Issue by slimski** [DigitalSymphony/DSLoadable#4]
It would be great to convert this pod to actual swift version. I can do it and send a Pull Request

**Comment by MaherKSantina** [comment]
Thanks @slimski for raising this issue! I was meaning to do that but then I just got distracted
there's a PR actually for that I'll merge soon and let you know!

**Comment by MaherKSantina** [comment]
@slimski I have updated the pod to version 1.0.0 which uses swift 4.2! Please let me know if it works out for you and feel free to close this issue if it does.

Thank you for your contribution and thank you for supporting this pod! 🙏

**Comment by slimski** [comment]
Thank you for so fast fix. Now everything works great!

**Comment by MaherKSantina** [comment]
No worries @slimski I'm glad I could help! :+1:
